services:
  web:
    image: odoo:16
    depends_on:
      - db
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    command:
      [
        "sh",
        "-c",
        "pip3 install -r /etc/odoo/requirements.txt && python3 -m debugpy --listen 0.0.0.0:5680 /usr/bin/odoo -c /etc/odoo/odoo.conf --dev xml"
      ]
    ports:
      - "5680:5680"
      - "8069:8069"
      - "8072:8072"
      - "8071:8071"
    networks:
      - dbNetwork
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - dbNetwork
volumes:
  odoo-web-data:
  odoo-db-data:
networks:
  dbNetwork:
    driver: bridge